### ISSUE TITLE
URL points to unmaintained webpage

### ISSUE THREAD

**Issue by mavit** [jhgorrell/ssh-config-mode-el#10]
The URL package attribute points to http://www.mahalito.net/~harley/elisp/ssh-config-mode.el, but this is an out of date version, from 2008.  Page http://www.mahalito.net/~harley/elisp/ does not link back to the currently maintained version at https://github.com/jhgorrell/ssh-config-mode-el/.

**Comment by jhgorrell** [comment]
Thanks! updated url to point to github.
