### ISSUE TITLE
UI is jarred by ssh-config-mode

### ISSUE THREAD

**Issue by seanfarley** [jhgorrell/ssh-config-mode-el#25]
Not sure what is going on so I'll just post some before / after screenshots:

(before `ssh-config-mode`)
<img width="1440" alt="Screen Shot 2020-06-14 at 8 42 36 PM" src="https://user-images.githubusercontent.com/20887/84616132-e720fd80-ae7f-11ea-8eaf-824cfc123628.png">

(after `ssh-config-mode`)
<img width="1440" alt="Screen Shot 2020-06-14 at 8 42 50 PM" src="https://user-images.githubusercontent.com/20887/84616147-f142fc00-ae7f-11ea-9827-5ba24f9ef028.png">

It seems the modeline was modified and line numbers are gone.

**Comment by jhgorrell** [comment]
Wow - that shouldnt happen.

Tried it on a couple of versions and wasnt able to replicate it.
Would you give me some more information about your environment?
(os, emacs ver, etc...)

**Comment by seanfarley** [comment]
It seems to happen because of [`(kill-all-local-variables)`](https://github.com/jhgorrell/ssh-config-mode-el/blob/64ed50791b82dd77c239bdc4c7070847d1c6cab6/ssh-config-mode.el#L200). There's some other funky stuff that happens because `ssh-config-mode` doesn't derive from another mode (such as `conf-mode` or `prog-mode`). I'm still not sure why the mode-line is changed but you're not messing with that variable so it must be in the framework I'm using.

**Comment by jhgorrell** [comment]
That is a bummer - I have had to track down interactions like that before.
It was a bunch of iterating over what modes were loaded and when, not fun.

Wish there was something like `git bisect` which worked on emacs configs. :)

**Comment by seanfarley** [comment]
> That is a bummer - I have had to track down interactions like that before.
> It was a bunch of iterating over what modes were loaded and when, not fun.
It wasn't too bad. The culprit for everything but the mode-line is your call to `(kill-all-local-variables)`. Removing that call fixes things for me.

The git branch was because your mode doesn't derive from another mode.

**Comment by seanfarley** [comment]
To be honest, after digging into this code, I realized that emacs has a built-in `conf-mode` which does nearly all I want. All I had to do was take your ssh keyword list and add it to the `.ssh/config` file keywords (I also added a missing keyword of `KeepAlive`):

```emacs-lisp
(require 'conf-mode)
(setq ssh-conf-keywords
      (string-join `("AddKeysToAgent"
                     "AddressFamily"
                     "BadOption"
                     "BatchMode"
                     "BindAddress"
                     "BindInterface"
                     "CASignatureAlgorithms"
                     "CanonicalDomains"
                     "CanonicalizeFallbackLocal"
                     "CanonicalizeHostname"
                     "CanonicalizeMaxDots"
                     "CanonicalizePermittedCNAMEs"
                     "CertificateFile"
                     "ChallengeResponseAuthentication"
                     "CheckHostIP"
                     "Ciphers"
                     "ClearAllForwardings"
                     "Compression"
                     "ConnectTimeout"
                     "ConnectionAttempts"
                     "ControlMaster"
                     "ControlPath"
                     "ControlPersist"
                     "Deprecated"
                     "DynamicForward"
                     "EnableSSHKeysign"
                     "EscapeChar"
                     "ExitOnForwardFailure"
                     "FingerprintHash"
                     "ForwardAgent"
                     "ForwardX11"
                     "ForwardX11Timeout"
                     "ForwardX11Trusted"
                     "GatewayPorts"
                     "GlobalKnownHostsFile"
                     "GssAuthentication"
                     "GssDelegateCreds"
                     "HashKnownHosts"
                     "Host"
                     "HostKeyAlgorithms"
                     "HostKeyAlias"
                     "HostbasedAuthentication"
                     "HostbasedKeyTypes"
                     "Hostname"
                     "IPQoS"
                     "IdentitiesOnly"
                     "IdentityAgent"
                     "IdentityFile"
                     "Ignore"
                     "IgnoreUnknown"
                     "IgnoredUnknownOption"
                     "Include"
                     "KbdInteractiveAuthentication"
                     "KbdInteractiveDevices"
                     "KeepAlive"
                     "KexAlgorithms"
                     "LocalCommand"
                     "LocalForward"
                     "LogFacility"
                     "LogLevel"
                     "Macs"
                     "Match"
                     "NoHostAuthenticationForLocalhost"
                     "NumberOfPasswordPrompts"
                     "PKCS11Provider"
                     "PasswordAuthentication"
                     "PermitLocalCommand"
                     "Port"
                     "PreferredAuthentications"
                     "ProxyCommand"
                     "ProxyJump"
                     "ProxyUseFdpass"
                     "PubkeyAcceptedKeyTypes"
                     "PubkeyAuthentication"
                     "RekeyLimit"
                     "RemoteCommand"
                     "RemoteForward"
                     "RequestTTY"
                     "RevokedHostKeys"
                     "SecurityKeyProvider"
                     "SendEnv"
                     "ServerAliveCountMax"
                     "ServerAliveInterval"
                     "SetEnv"
                     "StreamLocalBindMask"
                     "StreamLocalBindUnlink"
                     "StrictHostKeyChecking"
                     "TCPKeepAlive"
                     "Tunnel"
                     "TunnelDevice"
                     "Unsupported"
                     "UpdateHostkeys"
                     "User"
                     "UserKnownHostsFile"
                     "VerifyHostKeyDNS"
                     "VisualHostKey"
                     "XAuthLocation") "\\|"))

(add-to-list 'conf-space-keywords-alist
             `("/config\\'" . ,ssh-conf-keywords))
```

Maybe this mode could derive from that `conf-mode` and re-use the same logic?

**Comment by seanfarley** [comment]
Ok, I made a PR with some ideas for improving the mode; hopefully they work for you!

**Comment by seanfarley** [comment]
There's no fix for the line numbers not showing up since you only want to inherit from `fundamental-mode`. I'll just have to monkey patch this.
