### ISSUE TITLE
Regex for coloring *still* broken

### ISSUE THREAD

**Issue by seanfarley** [jhgorrell/ssh-config-mode-el#28]
Even after you updated the regex, it didn't fix ipv6 nor hostnames encapsulated by brackets:

<img width="477" alt="Screen Shot 2020-11-16 at 7 53 32 PM" src="https://user-images.githubusercontent.com/20887/99335591-f4c71e80-2835-11eb-878d-a6e96fb81397.png">

**Comment by jhgorrell** [comment]
Thanks for the report - I added these to `ssh-known-hosts-font-lock-keywords`.
LMK if they work for you.

**Comment by seanfarley** [comment]
Thanks for the update! There are still some missing keywords; photos attached:

<img width="413" alt="Screen Shot 2021-04-27 at 3 29 29 PM" src="https://user-images.githubusercontent.com/20887/116308744-b9256e80-a75c-11eb-87af-f36aa4ae7b37.png">
<img width="488" alt="Screen Shot 2021-04-27 at 3 29 41 PM" src="https://user-images.githubusercontent.com/20887/116308748-b9be0500-a75c-11eb-9e57-b2786b170be3.png">
<img width="449" alt="Screen Shot 2021-04-27 at 3 29 47 PM" src="https://user-images.githubusercontent.com/20887/116308750-ba569b80-a75c-11eb-9f87-8597c71bba3c.png">

**Comment by jhgorrell** [comment]
Added your examples to the test file, then reworked the regexps to match them.

Let me know if you find any which dont work.

**Comment by seanfarley** [comment]
Nice! Those now work and there is only one line that wasn't highlighted:

<img width="611" alt="Screen Shot 2021-04-28 at 12 31 14 PM" src="https://user-images.githubusercontent.com/20887/116447498-e92c4a80-a80c-11eb-9151-682121788710.png">

**Comment by seanfarley** [comment]
Thanks for your work!

**Comment by jhgorrell** [comment]
Ok - I had a "+" which should have been a "*"; so the single char hostname wasnt matched.
Good catch.

If this matches everything, I think this ticket could be closed. - Glad i could help!

**Comment by seanfarley** [comment]
Yep! Works for me, now! Thanks!
