### ISSUE TITLE
get-keywords grabs wrong data

### ISSUE THREAD

**Issue by scop** [jhgorrell/ssh-config-mode-el#32]
get-keywords grabs the "opcodes" from https://github.com/openssh/openssh-portable/blob/f5fc6a4c3404bbf65c21ca6361853b33d78aa87e/readconf.c#L142, but that's not what we should be treating as config keywords.

Instead, we should be parsing the config _names_, i.e. the first members of the `keywords` struct: https://github.com/openssh/openssh-portable/blob/f5fc6a4c3404bbf65c21ca6361853b33d78aa87e/readconf.c#L182

One example issue caused by this: we have `GssAuthentication` as a keyword, but no such keyword exists -- it's `gssapiauthentication`: https://github.com/openssh/openssh-portable/blob/f5fc6a4c3404bbf65c21ca6361853b33d78aa87e/readconf.c#L207

**Comment by jhgorrell** [comment]
Thanks for pointing this out -- Will fix that!

**Comment by jhgorrell** [comment]
Think this will fix the problem, let me know if it looks ok to you.

**Comment by scop** [comment]
LGTM, case insensitive diff of the keywords list from before and after confirms. Thanks!
