### ISSUE TITLE
Which parent?

### ISSUE THREAD

**Issue by grettke** [jhgorrell/ssh-config-mode-el#7]
Hi. I'm trying to set up a mode hook for the parent of ssh-config-mode. Usually it is programming mode or even fundamental mode. What is the best way to set up something like that for ssh-config-mode? Can it be derived from one of those?

**Comment by jhgorrell** [comment]
Hi! `ssh-config-mode` doesnt have a parent mode. `ssh-config-mode-hook` should be sufficient - if not, let me know your use case.

**Comment by jhgorrell** [comment]
Reopen if this is still a problem.

**Comment by grettke** [comment]
@jhgorrell Gotcha. Thank you!

**Comment by jhgorrell** [comment]
happy to help!

**Comment by NOBUTOKA** [comment]
I was wondering if it might make sense for ssh-config-mode to derive from conf-mode.
I tried a local experiment by just changing the parent of define-derived-mode to conf-mode, and it seems to work fine for me so far, and it would let me reuse my existing conf-mode-hook settings with SSH config files. 

What do you think?
