### ISSUE TITLE
File ssh-config-keywords.txt is missed on MELPA

### ISSUE THREAD

**Issue by boykov** [jhgorrell/ssh-config-mode-el#9]
I installed the package from MELPA and had to manually copy this file from github.

**Comment by jhgorrell** [comment]
Waiting for upstream fix: https://github.com/melpa/melpa/pull/4717

**Comment by jhgorrell** [comment]
upstream merged - should be working once the new package is built.

**Comment by jhgorrell** [comment]
The package is rebuilt.
